site_name: SmoothMQ
site_url: https://docs.smoothmq.com
nav:
  # - AWS SQS SDKs: sqs
#   - index.md
#   - sqs.md
#   - configuration.md
theme:
  name: material
  palette:
    primary: black
  font:
    text: Inter
  features:
    - navigation.sections
    # - navigation.path
    - navigation.expand
    # - navigation.tabs
    # - content.tabs.link
    # - navigation.tabs.sticky
repo_url: https://github.com/poundifdef/smoothmq
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - markdown_grid_tables